### ISSUE TITLE
Bootstrap not very responsive

### ISSUE THREAD

**Issue by darellrazk** [jailsonsb2/RadioPlayer-AzuraCast#1]
Trying to build an app around the radio player, where to adjust this one? Thanks
![image](https://github.com/jailsonsb2/RadioPlayer-AzuraCast/assets/171890474/e3f46913-5580-45b2-a5b7-997ad5c70733)

**Comment by jailsonsb2** [comment]
![image](https://github.com/jailsonsb2/RadioPlayer-AzuraCast/assets/13502945/5b3810d7-409c-4315-b1cb-35ed5d35ef59)
Hi friend, this should solve it!
